In [2]:
import numpy as np
import pandas as pd

In [54]:
ar1 = np.array([1,2,3])
ar2 = np.array([1,2,3])
ar1_names = ["Fuck", "you", "bitch!"]
ar2_names = ["bitch!", "you", "Fuck"]
ps1 = pd.Series(ar1, index=ar1_names)
ps2 = pd.Series(ar2, index=ar2_names)
ps1 += ps2
print(ps2.get("Fuck", 6))
for ind in ps1.index:
    print(ind)
print(np.array(ps1))

3
Fuck
you
bitch!
[4 4 4]


In [10]:
class C(object):
    
    l = [1,2,3]
    
    def __iter__(self):
        for li in self.l:
            yield(li)


c = C()
for li in c:
    print(li)

1
2
3


In [56]:
ar = np.array([[1,2], [4,6]])
print(ar/3.0)
ar[1] = [7,8]
ar

[[0.33333333 0.66666667]
 [1.33333333 2.        ]]


array([[1, 2],
       [7, 8]])

In [29]:
s = {1,2,3}
for i, x in enumerate(s):
    print(i, x)

(0, 1)
(1, 2)
(2, 3)


In [30]:
d = {"a": 2, "b": 3}
len(d)

2

In [39]:
np.empty((4,4))

array([[4.64314333e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])