In [1]:
import os
import re
import time
import json
import string
import random
import multiprocessing as mp
from collections import defaultdict

import numpy as np
import pandas as pd

In [9]:
ar1 = np.array([1,2,3])
ar2 = np.array([1,2,0])
ar1_names = ["Fuck", "you", "bitch!"]
ar2_names = ["bitch!", "you", "Fuck"]
ps1 = pd.Series(ar1, index=ar1_names)
ps2 = pd.Series(ar2, index=ar2_names)
ps1 += ps2
print(ps2.get("Fuck", 6))
for ind in ps1.index:
    print(ind)
print(np.array(ps1))
ps1 * 6.0

0
Fuck
you
bitch!
[1 4 4]


Fuck       6.0
you       24.0
bitch!    24.0
dtype: float64

In [17]:
ps1[ps1 >= 1.0].mean()

3.0

In [13]:
list(filter(lambda x: x!=1, [1,2,3]))

[2, 3]

In [56]:
ar = np.array([[1,2], [4,6]])
print(ar/3.0)
ar[1] = [7,8]
ar

[[0.33333333 0.66666667]
 [1.33333333 2.        ]]


array([[1, 2],
       [7, 8]])

In [29]:
s = {1,2,3}
for i, x in enumerate(s):
    print(i, x)

(0, 1)
(1, 2)
(2, 3)


In [30]:
d = {"a": 2, "b": 3}
len(d)

2

In [63]:
np.empty((20,20), dtype=float)

array([[6.94203904e-310, 6.94203904e-310, 4.64314334e-310,
        4.64314334e-310, 4.94065646e-324, 4.64314334e-310,
        1.01855798e-312, 6.94203626e-310, 1.10343781e-312,
        9.54898106e-313, 1.03977794e-312, 9.33678148e-313,
        4.94065646e-324, 1.20953760e-312, 4.64314334e-310,
        6.94203756e-310, 1.01855798e-312, 2.14321575e-312,
        1.08221785e-312, 4.94065646e-324],
       [4.94065646e-324, 4.64314334e-310, 9.88131292e-324,
        4.64314334e-310, 4.64314334e-310, 4.64313899e-310,
        4.64314241e-310, 1.03977794e-312, 4.64314241e-310,
        2.33419537e-312, 6.79038653e-313, 2.12199579e-313,
        6.79038653e-313, 4.64314241e-310, 9.76118064e-313,
        4.64314241e-310, 1.08221785e-312, 1.12465777e-312,
        2.75859453e-313, 9.54898106e-313],
       [4.64314334e-310, 9.33678148e-313, 4.64314334e-310,
        1.03977794e-312, 1.08221785e-312, 2.12199579e-313,
        4.94065646e-324, 4.64314334e-310, 1.08221785e-312,
        6.94203914e-310, 6.79

In [71]:
pd.DataFrame([[0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.237117, 0.240802, 0.237117, 0.240802, 0.0, 0.237117, 0.24355, 0.236722, 0.240802, 0.240802, 0.242005, 0.237769, 0.245375, 0.237117, 0.24769, 0.237117, 0.234684, 0.237117, 0.237051, 0.237466], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.068064, 0.062433, 0.068064, 0.062433, 0.24355, 0.068064, 0.0, 0.070382, 0.062433, 0.062433, 0.069689, 0.076808, 0.065729, 0.068064, 0.075051, 0.068064, 0.067742, 0.06877, 0.069537, 0.065905], [0.068148, 0.058917, 0.068148, 0.058917, 0.236722, 0.068148, 0.070382, 0.0, 0.058917, 0.058917, 0.067635, 0.042237, 0.063768, 0.068148, 0.083614, 0.068148, 0.068568, 0.068855, 0.06678, 0.066193], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.030437, 0.023706, 0.030437, 0.023706, 0.242005, 0.030437, 0.069689, 0.067635, 0.023706, 0.023706, 0.0, 0.069594, 0.030444, 0.030437, 0.078059, 0.030437, 0.029909, 0.03111, 0.028433, 0.022386], [0.07073, 0.064511, 0.07073, 0.064511, 0.237769, 0.07073, 0.076808, 0.042237, 0.064511, 0.064511, 0.069594, 0.0, 0.06884, 0.07073, 0.079849, 0.07073, 0.069681, 0.071437, 0.068031, 0.065976], [0.021674, 0.016347, 0.021674, 0.016347, 0.245375, 0.021674, 0.065729, 0.063768, 0.016347, 0.016347, 0.030444, 0.06884, 0.0, 0.021674, 0.076552, 0.021674, 0.021803, 0.022339, 0.023033, 0.026396], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.084353, 0.075173, 0.084353, 0.075173, 0.24769, 0.084353, 0.075051, 0.083614, 0.075173, 0.075173, 0.078059, 0.079849, 0.076552, 0.084353, 0.0, 0.084353, 0.083432, 0.085071, 0.083803, 0.083782], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.0, 0.020439, 0.0, 0.020439, 0.234684, 0.0, 0.067742, 0.068568, 0.020439, 0.020439, 0.029909, 0.069681, 0.021803, 0.0, 0.083432, 0.0, 0.0, 0.00065, 0.007193, 0.024475], [0.000646, 0.020981, 0.000646, 0.020981, 0.237117, 0.000646, 0.06877, 0.068855, 0.020981, 0.020981, 0.03111, 0.071437, 0.022339, 0.000646, 0.085071, 0.000646, 0.00065, 0.0, 0.007803, 0.026361], [0.007151, 0.019017, 0.007151, 0.019017, 0.237051, 0.007151, 0.069537, 0.06678, 0.019017, 0.019017, 0.028433, 0.068031, 0.023033, 0.007151, 0.083803, 0.007151, 0.007193, 0.007803, 0.0, 0.021693], [0.025693, 0.019722, 0.025693, 0.019722, 0.237466, 0.025693, 0.065905, 0.066193, 0.019722, 0.019722, 0.022386, 0.065976, 0.026396, 0.025693, 0.083782, 0.025693, 0.024475, 0.026361, 0.021693, 0.0]])

0         1         2         3         4         5         6   \
0   0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
1   0.020318  0.000000  0.020318  0.000000  0.240802  0.020318  0.062433   
2   0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
3   0.020318  0.000000  0.020318  0.000000  0.240802  0.020318  0.062433   
4   0.237117  0.240802  0.237117  0.240802  0.000000  0.237117  0.243550   
5   0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
6   0.068064  0.062433  0.068064  0.062433  0.243550  0.068064  0.000000   
7   0.068148  0.058917  0.068148  0.058917  0.236722  0.068148  0.070382   
8   0.020318  0.000000  0.020318  0.000000  0.240802  0.020318  0.062433   
9   0.020318  0.000000  0.020318  0.000000  0.240802  0.020318  0.062433   
10  0.030437  0.023706  0.030437  0.023706  0.242005  0.030437  0.069689   
11  0.070730  0.064511  0.070730  0.064511  0.237769  0.070730  0.076808   
12  0.021674  0.016347  0.021674  0.016347  0.245375  0.021674  0.065729   
13  0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
14  0.084353  0.075173  0.084353  0.075173  0.247690  0.084353  0.075051   
15  0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
16  0.000000  0.020439  0.000000  0.020439  0.234684  0.000000  0.067742   
17  0.000646  0.020981  0.000646  0.020981  0.237117  0.000646  0.068770   
18  0.007151  0.019017  0.007151  0.019017  0.237051  0.007151  0.069537   
19  0.025693  0.019722  0.025693  0.019722  0.237466  0.025693  0.065905   

          7         8         9         10        11        12        13  \
0   0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
1   0.058917  0.000000  0.000000  0.023706  0.064511  0.016347  0.020318   
2   0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
3   0.058917  0.000000  0.000000  0.023706  0.064511  0.016347  0.020318   
4   0.236722  0.240802  0.240802  0.242005  0.237769  0.245375  0.237117   
5   0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
6   0.070382  0.062433  0.062433  0.069689  0.076808  0.065729  0.068064   
7   0.000000  0.058917  0.058917  0.067635  0.042237  0.063768  0.068148   
8   0.058917  0.000000  0.000000  0.023706  0.064511  0.016347  0.020318   
9   0.058917  0.000000  0.000000  0.023706  0.064511  0.016347  0.020318   
10  0.067635  0.023706  0.023706  0.000000  0.069594  0.030444  0.030437   
11  0.042237  0.064511  0.064511  0.069594  0.000000  0.068840  0.070730   
12  0.063768  0.016347  0.016347  0.030444  0.068840  0.000000  0.021674   
13  0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
14  0.083614  0.075173  0.075173  0.078059  0.079849  0.076552  0.084353   
15  0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
16  0.068568  0.020439  0.020439  0.029909  0.069681  0.021803  0.000000   
17  0.068855  0.020981  0.020981  0.031110  0.071437  0.022339  0.000646   
18  0.066780  0.019017  0.019017  0.028433  0.068031  0.023033  0.007151   
19  0.066193  0.019722  0.019722  0.022386  0.065976  0.026396  0.025693   

          14        15        16        17        18        19  
0   0.084353  0.000000  0.000000  0.000646  0.007151  0.025693  
1   0.075173  0.020318  0.020439  0.020981  0.019017  0.019722  
2   0.084353  0.000000  0.000000  0.000646  0.007151  0.025693  
3   0.075173  0.020318  0.020439  0.020981  0.019017  0.019722  
4   0.247690  0.237117  0.234684  0.237117  0.237051  0.237466  
5   0.084353  0.000000  0.000000  0.000646  0.007151  0.025693  
6   0.075051  0.068064  0.067742  0.068770  0.069537  0.065905  
7   0.083614  0.068148  0.068568  0.068855  0.066780  0.066193  
8   0.075173  0.020318  0.020439  0.020981  0.019017  0.019722  
9   0.075173  0.020318  0.020439  0.020981  0.019017  0.019722  
10  0.078059  0.030437  0.029909  0.031110  0.028433  0.022386  
11  0.079849  0.070730  0.069681  0.

In [70]:
with open("f.json", "w") as f:
    json.dump([[0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.237117, 0.240802, 0.237117, 0.240802, 0.0, 0.237117, 0.24355, 0.236722, 0.240802, 0.240802, 0.242005, 0.237769, 0.245375, 0.237117, 0.24769, 0.237117, 0.234684, 0.237117, 0.237051, 0.237466], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.068064, 0.062433, 0.068064, 0.062433, 0.24355, 0.068064, 0.0, 0.070382, 0.062433, 0.062433, 0.069689, 0.076808, 0.065729, 0.068064, 0.075051, 0.068064, 0.067742, 0.06877, 0.069537, 0.065905], [0.068148, 0.058917, 0.068148, 0.058917, 0.236722, 0.068148, 0.070382, 0.0, 0.058917, 0.058917, 0.067635, 0.042237, 0.063768, 0.068148, 0.083614, 0.068148, 0.068568, 0.068855, 0.06678, 0.066193], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.030437, 0.023706, 0.030437, 0.023706, 0.242005, 0.030437, 0.069689, 0.067635, 0.023706, 0.023706, 0.0, 0.069594, 0.030444, 0.030437, 0.078059, 0.030437, 0.029909, 0.03111, 0.028433, 0.022386], [0.07073, 0.064511, 0.07073, 0.064511, 0.237769, 0.07073, 0.076808, 0.042237, 0.064511, 0.064511, 0.069594, 0.0, 0.06884, 0.07073, 0.079849, 0.07073, 0.069681, 0.071437, 0.068031, 0.065976], [0.021674, 0.016347, 0.021674, 0.016347, 0.245375, 0.021674, 0.065729, 0.063768, 0.016347, 0.016347, 0.030444, 0.06884, 0.0, 0.021674, 0.076552, 0.021674, 0.021803, 0.022339, 0.023033, 0.026396], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.084353, 0.075173, 0.084353, 0.075173, 0.24769, 0.084353, 0.075051, 0.083614, 0.075173, 0.075173, 0.078059, 0.079849, 0.076552, 0.084353, 0.0, 0.084353, 0.083432, 0.085071, 0.083803, 0.083782], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.0, 0.020439, 0.0, 0.020439, 0.234684, 0.0, 0.067742, 0.068568, 0.020439, 0.020439, 0.029909, 0.069681, 0.021803, 0.0, 0.083432, 0.0, 0.0, 0.00065, 0.007193, 0.024475], [0.000646, 0.020981, 0.000646, 0.020981, 0.237117, 0.000646, 0.06877, 0.068855, 0.020981, 0.020981, 0.03111, 0.071437, 0.022339, 0.000646, 0.085071, 0.000646, 0.00065, 0.0, 0.007803, 0.026361], [0.007151, 0.019017, 0.007151, 0.019017, 0.237051, 0.007151, 0.069537, 0.06678, 0.019017, 0.019017, 0.028433, 0.068031, 0.023033, 0.007151, 0.083803, 0.007151, 0.007193, 0.007803, 0.0, 0.021693], [0.025693, 0.019722, 0.025693, 0.019722, 0.237466, 0.025693, 0.065905, 0.066193, 0.019722, 0.019722, 0.022386, 0.065976, 0.026396, 0.025693, 0.083782, 0.025693, 0.024475, 0.026361, 0.021693, 0.0]], f)

In [11]:
def func(x, y, **kwargs):
    print(x*y*kwargs.get("c", 5))
    
func(2, 3, **{"c": 6})

p = mp.Process(target=func, args=(2, 3), kwargs={"c": 6})
p.start()
p.join()

36
36


In [47]:
#sar = np.zeros(4, dtype=np.dtype([("f%s" % i, np.chararray) for i in range(5)]))
sar = np.array((4,dtype=np.string_)
print(sar)
sar[0] = 6
print(sar)

4


IndexError: too many indices for array

In [4]:
sar = np.zeros(4, dtype="S7")
print(sar)
sar[0] = "abc"
sar[1] = "defghij"
sar[2] = "klmnopqr"
print(sar)


['' '' '' '']
['abc' 'defghij' 'klmnopq' '']


3

In [7]:
np.mean([1,2,3,4])

2.5

In [77]:
memar = np.memmap("data.dat", dtype="S7", mode='w+', shape=4)
memar[0] = "abc"
memar[1] = "defghij"
memar.shape

(4,)

In [125]:
ar = np.zeros(100000, dtype="S1000")
memar = np.memmap("data.dat", dtype="S1000", mode='w+', shape=ar.shape[0])
for i in range(ar.shape[0]):
    rands = "".join(str(np.random.randint(10)) for i in range(1000))
    memar[i], ar[i] = rands, rands

In [126]:
t1 = time.clock()
n_it = 0
while n_it < 10000:
    s = ar[np.random.randint(ar.shape[0])]
    n_it += 1
    if n_it % 10 == 0:
        print(n_it)
t2 = time.clock()
print(t2-t1)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1320
1330
1340
1350
1360
1370
1380
1390
1400
1410
1420
1430
1440
1450
1460
1470
1480
1490
1500
1510
1520
1530
1540
1550
1560
1570
1580
1590
1600
1610
1620
1630
1640
1650
1660
1670
1680
1690
1700
1710
1720
1730
1740
1750
1760
1770
1780
1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010
2020
2030
2040
2050
2060
2070
2080
2090
2100
2110
2120
2130
2140
2150
2160
2170
2180
2190
2200
2210
222

In [127]:
t1 = time.clock()
n_it = 0
while n_it < 10000:
    s = memar[np.random.randint(ar.shape[0])]
    n_it += 1
    if n_it % 10 == 0:
        print(n_it)
t2 = time.clock()
print(t2-t1)

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1320
1330
1340
1350
1360
1370
1380
1390
1400
1410
1420
1430
1440
1450
1460
1470
1480
1490
1500
1510
1520
1530
1540
1550
1560
1570
1580
1590
1600
1610
1620
1630
1640
1650
1660
1670
1680
1690
1700
1710
1720
1730
1740
1750
1760
1770
1780
1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010
2020
2030
2040
2050
2060
2070
2080
2090
2100
2110
2120
2130
2140
2150
2160
2170
2180
2190
2200
2210
222

In [173]:
ar = np.array([[1.5, 2.8, 3.1], [-1.0,-5.7, 6.9]])
ar1 = ar.copy()
ar1[ar1 < 0.0] = np.median(ar)
print(ar)
print(ar1)
print(np.median(ar), np.median(ar[ar >= 0.0]))

[[ 1.5  2.8  3.1]
 [-1.  -5.7  6.9]]
[[1.5  2.8  3.1 ]
 [2.15 2.15 6.9 ]]
(2.15, 2.95)


In [153]:
np.dtype("S1000")

dtype('S1000')

In [181]:
ar = np.array([1.5, 2.8, 3.1,-1.0,-5.7, 6.9])
#type(ar)
assert isinstance(ar, np.ndarray), "ERROR: value for 'matr' argument should be numpy.ndarray"

In [22]:
class SliceC(object):
    
    def __getitem__(self, item):
        return item
    
sc = SliceC()
slc = sc[3:6]
slc.stop

6

In [25]:
l = [1,2,3,4,5,6]
l[slice(1, 5)]

[2, 3, 4, 5]

In [36]:
l[:108]

[1, 2, 3, 4, 5, 6]

In [26]:
filter(lambda x: x > 2, l)

[3, 4, 5, 6]

In [33]:
s = "abccbbac"
print(re.sub("(ab|cb|ac)", "*", s))
m = re.search("ccbb", s)
m.start(), m.end()

*c*b*


(2, 6)

In [34]:
for i, si in enumerate(s):
    print(i, si)

(0, 'a')
(1, 'b')
(2, 'c')
(3, 'c')
(4, 'b')
(5, 'b')
(6, 'a')
(7, 'c')
