In [67]:
import json
from collections import defaultdict

import numpy as np
import pandas as pd

In [75]:
ar1 = np.array([1,2,3])
ar2 = np.array([1,2,0])
ar1_names = ["Fuck", "you", "bitch!"]
ar2_names = ["bitch!", "you", "Fuck"]
ps1 = pd.Series(ar1, index=ar1_names)
ps2 = pd.Series(ar2, index=ar2_names)
ps1 += ps2
print(ps2.get("Fuck", 6))
for ind in ps1.index:
    print(ind)
print(np.array(ps1))
ps1 * 6.0

0
Fuck
you
bitch!
[1 4 4]


Fuck       6.0
you       24.0
bitch!    24.0
dtype: float64

In [10]:
class C(object):
    
    l = [1,2,3]
    
    def __iter__(self):
        for li in self.l:
            yield(li)


c = C()
for li in c:
    print(li)

1
2
3


In [56]:
ar = np.array([[1,2], [4,6]])
print(ar/3.0)
ar[1] = [7,8]
ar

[[0.33333333 0.66666667]
 [1.33333333 2.        ]]


array([[1, 2],
       [7, 8]])

In [29]:
s = {1,2,3}
for i, x in enumerate(s):
    print(i, x)

(0, 1)
(1, 2)
(2, 3)


In [30]:
d = {"a": 2, "b": 3}
len(d)

2

In [63]:
np.empty((20,20), dtype=float)

array([[6.94203904e-310, 6.94203904e-310, 4.64314334e-310,
        4.64314334e-310, 4.94065646e-324, 4.64314334e-310,
        1.01855798e-312, 6.94203626e-310, 1.10343781e-312,
        9.54898106e-313, 1.03977794e-312, 9.33678148e-313,
        4.94065646e-324, 1.20953760e-312, 4.64314334e-310,
        6.94203756e-310, 1.01855798e-312, 2.14321575e-312,
        1.08221785e-312, 4.94065646e-324],
       [4.94065646e-324, 4.64314334e-310, 9.88131292e-324,
        4.64314334e-310, 4.64314334e-310, 4.64313899e-310,
        4.64314241e-310, 1.03977794e-312, 4.64314241e-310,
        2.33419537e-312, 6.79038653e-313, 2.12199579e-313,
        6.79038653e-313, 4.64314241e-310, 9.76118064e-313,
        4.64314241e-310, 1.08221785e-312, 1.12465777e-312,
        2.75859453e-313, 9.54898106e-313],
       [4.64314334e-310, 9.33678148e-313, 4.64314334e-310,
        1.03977794e-312, 1.08221785e-312, 2.12199579e-313,
        4.94065646e-324, 4.64314334e-310, 1.08221785e-312,
        6.94203914e-310, 6.79

In [71]:
pd.DataFrame([[0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.237117, 0.240802, 0.237117, 0.240802, 0.0, 0.237117, 0.24355, 0.236722, 0.240802, 0.240802, 0.242005, 0.237769, 0.245375, 0.237117, 0.24769, 0.237117, 0.234684, 0.237117, 0.237051, 0.237466], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.068064, 0.062433, 0.068064, 0.062433, 0.24355, 0.068064, 0.0, 0.070382, 0.062433, 0.062433, 0.069689, 0.076808, 0.065729, 0.068064, 0.075051, 0.068064, 0.067742, 0.06877, 0.069537, 0.065905], [0.068148, 0.058917, 0.068148, 0.058917, 0.236722, 0.068148, 0.070382, 0.0, 0.058917, 0.058917, 0.067635, 0.042237, 0.063768, 0.068148, 0.083614, 0.068148, 0.068568, 0.068855, 0.06678, 0.066193], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.030437, 0.023706, 0.030437, 0.023706, 0.242005, 0.030437, 0.069689, 0.067635, 0.023706, 0.023706, 0.0, 0.069594, 0.030444, 0.030437, 0.078059, 0.030437, 0.029909, 0.03111, 0.028433, 0.022386], [0.07073, 0.064511, 0.07073, 0.064511, 0.237769, 0.07073, 0.076808, 0.042237, 0.064511, 0.064511, 0.069594, 0.0, 0.06884, 0.07073, 0.079849, 0.07073, 0.069681, 0.071437, 0.068031, 0.065976], [0.021674, 0.016347, 0.021674, 0.016347, 0.245375, 0.021674, 0.065729, 0.063768, 0.016347, 0.016347, 0.030444, 0.06884, 0.0, 0.021674, 0.076552, 0.021674, 0.021803, 0.022339, 0.023033, 0.026396], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.084353, 0.075173, 0.084353, 0.075173, 0.24769, 0.084353, 0.075051, 0.083614, 0.075173, 0.075173, 0.078059, 0.079849, 0.076552, 0.084353, 0.0, 0.084353, 0.083432, 0.085071, 0.083803, 0.083782], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.0, 0.020439, 0.0, 0.020439, 0.234684, 0.0, 0.067742, 0.068568, 0.020439, 0.020439, 0.029909, 0.069681, 0.021803, 0.0, 0.083432, 0.0, 0.0, 0.00065, 0.007193, 0.024475], [0.000646, 0.020981, 0.000646, 0.020981, 0.237117, 0.000646, 0.06877, 0.068855, 0.020981, 0.020981, 0.03111, 0.071437, 0.022339, 0.000646, 0.085071, 0.000646, 0.00065, 0.0, 0.007803, 0.026361], [0.007151, 0.019017, 0.007151, 0.019017, 0.237051, 0.007151, 0.069537, 0.06678, 0.019017, 0.019017, 0.028433, 0.068031, 0.023033, 0.007151, 0.083803, 0.007151, 0.007193, 0.007803, 0.0, 0.021693], [0.025693, 0.019722, 0.025693, 0.019722, 0.237466, 0.025693, 0.065905, 0.066193, 0.019722, 0.019722, 0.022386, 0.065976, 0.026396, 0.025693, 0.083782, 0.025693, 0.024475, 0.026361, 0.021693, 0.0]])

0         1         2         3         4         5         6   \
0   0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
1   0.020318  0.000000  0.020318  0.000000  0.240802  0.020318  0.062433   
2   0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
3   0.020318  0.000000  0.020318  0.000000  0.240802  0.020318  0.062433   
4   0.237117  0.240802  0.237117  0.240802  0.000000  0.237117  0.243550   
5   0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
6   0.068064  0.062433  0.068064  0.062433  0.243550  0.068064  0.000000   
7   0.068148  0.058917  0.068148  0.058917  0.236722  0.068148  0.070382   
8   0.020318  0.000000  0.020318  0.000000  0.240802  0.020318  0.062433   
9   0.020318  0.000000  0.020318  0.000000  0.240802  0.020318  0.062433   
10  0.030437  0.023706  0.030437  0.023706  0.242005  0.030437  0.069689   
11  0.070730  0.064511  0.070730  0.064511  0.237769  0.070730  0.076808   
12  0.021674  0.016347  0.021674  0.016347  0.245375  0.021674  0.065729   
13  0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
14  0.084353  0.075173  0.084353  0.075173  0.247690  0.084353  0.075051   
15  0.000000  0.020318  0.000000  0.020318  0.237117  0.000000  0.068064   
16  0.000000  0.020439  0.000000  0.020439  0.234684  0.000000  0.067742   
17  0.000646  0.020981  0.000646  0.020981  0.237117  0.000646  0.068770   
18  0.007151  0.019017  0.007151  0.019017  0.237051  0.007151  0.069537   
19  0.025693  0.019722  0.025693  0.019722  0.237466  0.025693  0.065905   

          7         8         9         10        11        12        13  \
0   0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
1   0.058917  0.000000  0.000000  0.023706  0.064511  0.016347  0.020318   
2   0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
3   0.058917  0.000000  0.000000  0.023706  0.064511  0.016347  0.020318   
4   0.236722  0.240802  0.240802  0.242005  0.237769  0.245375  0.237117   
5   0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
6   0.070382  0.062433  0.062433  0.069689  0.076808  0.065729  0.068064   
7   0.000000  0.058917  0.058917  0.067635  0.042237  0.063768  0.068148   
8   0.058917  0.000000  0.000000  0.023706  0.064511  0.016347  0.020318   
9   0.058917  0.000000  0.000000  0.023706  0.064511  0.016347  0.020318   
10  0.067635  0.023706  0.023706  0.000000  0.069594  0.030444  0.030437   
11  0.042237  0.064511  0.064511  0.069594  0.000000  0.068840  0.070730   
12  0.063768  0.016347  0.016347  0.030444  0.068840  0.000000  0.021674   
13  0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
14  0.083614  0.075173  0.075173  0.078059  0.079849  0.076552  0.084353   
15  0.068148  0.020318  0.020318  0.030437  0.070730  0.021674  0.000000   
16  0.068568  0.020439  0.020439  0.029909  0.069681  0.021803  0.000000   
17  0.068855  0.020981  0.020981  0.031110  0.071437  0.022339  0.000646   
18  0.066780  0.019017  0.019017  0.028433  0.068031  0.023033  0.007151   
19  0.066193  0.019722  0.019722  0.022386  0.065976  0.026396  0.025693   

          14        15        16        17        18        19  
0   0.084353  0.000000  0.000000  0.000646  0.007151  0.025693  
1   0.075173  0.020318  0.020439  0.020981  0.019017  0.019722  
2   0.084353  0.000000  0.000000  0.000646  0.007151  0.025693  
3   0.075173  0.020318  0.020439  0.020981  0.019017  0.019722  
4   0.247690  0.237117  0.234684  0.237117  0.237051  0.237466  
5   0.084353  0.000000  0.000000  0.000646  0.007151  0.025693  
6   0.075051  0.068064  0.067742  0.068770  0.069537  0.065905  
7   0.083614  0.068148  0.068568  0.068855  0.066780  0.066193  
8   0.075173  0.020318  0.020439  0.020981  0.019017  0.019722  
9   0.075173  0.020318  0.020439  0.020981  0.019017  0.019722  
10  0.078059  0.030437  0.029909  0.031110  0.028433  0.022386  
11  0.079849  0.070730  0.069681  0.

In [70]:
with open("f.json", "w") as f:
    json.dump([[0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.237117, 0.240802, 0.237117, 0.240802, 0.0, 0.237117, 0.24355, 0.236722, 0.240802, 0.240802, 0.242005, 0.237769, 0.245375, 0.237117, 0.24769, 0.237117, 0.234684, 0.237117, 0.237051, 0.237466], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.068064, 0.062433, 0.068064, 0.062433, 0.24355, 0.068064, 0.0, 0.070382, 0.062433, 0.062433, 0.069689, 0.076808, 0.065729, 0.068064, 0.075051, 0.068064, 0.067742, 0.06877, 0.069537, 0.065905], [0.068148, 0.058917, 0.068148, 0.058917, 0.236722, 0.068148, 0.070382, 0.0, 0.058917, 0.058917, 0.067635, 0.042237, 0.063768, 0.068148, 0.083614, 0.068148, 0.068568, 0.068855, 0.06678, 0.066193], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.020318, 0.0, 0.020318, 0.0, 0.240802, 0.020318, 0.062433, 0.058917, 0.0, 0.0, 0.023706, 0.064511, 0.016347, 0.020318, 0.075173, 0.020318, 0.020439, 0.020981, 0.019017, 0.019722], [0.030437, 0.023706, 0.030437, 0.023706, 0.242005, 0.030437, 0.069689, 0.067635, 0.023706, 0.023706, 0.0, 0.069594, 0.030444, 0.030437, 0.078059, 0.030437, 0.029909, 0.03111, 0.028433, 0.022386], [0.07073, 0.064511, 0.07073, 0.064511, 0.237769, 0.07073, 0.076808, 0.042237, 0.064511, 0.064511, 0.069594, 0.0, 0.06884, 0.07073, 0.079849, 0.07073, 0.069681, 0.071437, 0.068031, 0.065976], [0.021674, 0.016347, 0.021674, 0.016347, 0.245375, 0.021674, 0.065729, 0.063768, 0.016347, 0.016347, 0.030444, 0.06884, 0.0, 0.021674, 0.076552, 0.021674, 0.021803, 0.022339, 0.023033, 0.026396], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.084353, 0.075173, 0.084353, 0.075173, 0.24769, 0.084353, 0.075051, 0.083614, 0.075173, 0.075173, 0.078059, 0.079849, 0.076552, 0.084353, 0.0, 0.084353, 0.083432, 0.085071, 0.083803, 0.083782], [0.0, 0.020318, 0.0, 0.020318, 0.237117, 0.0, 0.068064, 0.068148, 0.020318, 0.020318, 0.030437, 0.07073, 0.021674, 0.0, 0.084353, 0.0, 0.0, 0.000646, 0.007151, 0.025693], [0.0, 0.020439, 0.0, 0.020439, 0.234684, 0.0, 0.067742, 0.068568, 0.020439, 0.020439, 0.029909, 0.069681, 0.021803, 0.0, 0.083432, 0.0, 0.0, 0.00065, 0.007193, 0.024475], [0.000646, 0.020981, 0.000646, 0.020981, 0.237117, 0.000646, 0.06877, 0.068855, 0.020981, 0.020981, 0.03111, 0.071437, 0.022339, 0.000646, 0.085071, 0.000646, 0.00065, 0.0, 0.007803, 0.026361], [0.007151, 0.019017, 0.007151, 0.019017, 0.237051, 0.007151, 0.069537, 0.06678, 0.019017, 0.019017, 0.028433, 0.068031, 0.023033, 0.007151, 0.083803, 0.007151, 0.007193, 0.007803, 0.0, 0.021693], [0.025693, 0.019722, 0.025693, 0.019722, 0.237466, 0.025693, 0.065905, 0.066193, 0.019722, 0.019722, 0.022386, 0.065976, 0.026396, 0.025693, 0.083782, 0.025693, 0.024475, 0.026361, 0.021693, 0.0]], f)

In [76]:
l1 = [1,2,3]
l2 = [4,5]
l1+l2

[1, 2, 3, 4, 5]